x-airflow-common: &airflow-common
  image: apache/airflow:2.9.0
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__FERNET_KEY=l9auRj5q6-93KRX6PeTCJcfMIMv3F0hpWwknQ82O_8k=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/weather_etl
    - _PIP_ADDITIONAL_REQUIREMENTS=apache-airflow-providers-postgres
    - PYTHONPATH=/opt/airflow/src
    GOOGLE_APPLICATION_CREDENTIALS: "/opt/airflow/keys/airflow-sa.json"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
    - ./keys:/opt/airflow/keys
  user: "${AIRFLOW_UID:-1000}:0"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 1s
      retries: 2

  airflow-init:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "
        echo 'â³ Waiting for Postgres...';
        sleep 1;
        airflow db migrate &&
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password admin
      "

  webserver:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: bash -c "  
        echo 'ðŸ§¹ Cleaning old PID...';
        rm -f /opt/airflow/airflow-webserver.pid &&
        echo 'ðŸš€ Starting Airflow Webserver...';
        airflow webserver
      "
    ports:
      - "8080:8080"

  scheduler:
    <<: *airflow-common
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: bash -c "
        echo 'ðŸ“… Starting Airflow Scheduler...';
        airflow scheduler
      "

volumes:
  postgres_data:
  dags_data:
  src_data:
  logs_data: